# -----------------------------------------------------
# Manual window resizing (SUPER + ALT + ARROWS)
# -----------------------------------------------------
dwindle {
    preserve_split = true # Prevents window sizes from resetting when opening new apps
}

# Resize horizontally (Moves the split line left/right)
binde = SUPER ALT, right, resizeactive, 40 0
binde = SUPER ALT, left, resizeactive, -40 0

# Resize vertically (In case you need it too)
binde = SUPER ALT, up, resizeactive, 0 -40
binde = SUPER ALT, down, resizeactive, 0 40